class ENOSChart{
constructor(host,opts={}){this.host=host;this.opts=opts;this.chart=null;this.candles=null;this.volume=null;this.overlay=null;this.paperLayer=null;this.symbol='';this.interval='';this.data=[];this.analysis=null;this.positions=[];this.drawings=[];this.tool='cursor';this.pending=[];this.countTimer=null;this.ro=null;this._layers()}
_layers(){this.host.innerHTML='<div class="chart-host"></div><svg class="svg-overlay"></svg><div class="paper-overlay"></div>';this.chartHost=this.host.querySelector('.chart-host');this.overlay=this.host.querySelector('.svg-overlay');this.paperLayer=this.host.querySelector('.paper-overlay')}
destroy(){if(this.countTimer)clearInterval(this.countTimer);if(this.ro)this.ro.disconnect();if(this.chart){try{this.chart.remove()}catch(e){}}this.chart=null;this._layers()}
precision(px){if(px>=1000)return[2,.01];if(px>=100)return[3,.001];if(px>=1)return[4,.0001];if(px>=.1)return[5,.00001];if(px>=.01)return[6,.000001];return[8,.00000001]}
mount(symbol,interval,data,analysis,positions=[]){this.destroy();this.symbol=symbol;this.interval=interval;this.data=data;this.analysis=analysis;this.positions=positions;const L=window.LightweightCharts;const last=data.length?data[data.length-1].close:1;const[p,m]=this.precision(last);this.chart=L.createChart(this.chartHost,{layout:{background:{type:'solid',color:'#041520'},textColor:'#86a8bc'},grid:{vertLines:{color:'#0b2939'},horzLines:{color:'#0b2939'}},crosshair:{mode:0,vertLine:{color:'#2d6c8d'},horzLine:{color:'#2d6c8d'}},rightPriceScale:{borderColor:'#16445d'},timeScale:{borderColor:'#16445d',timeVisible:true,secondsVisible:false,rightOffset:8,barSpacing:6},localization:{priceFormatter:v=>Number(v).toFixed(p)}});this.candles=this.chart.addSeries(L.CandlestickSeries,{upColor:'#00d9c5',downColor:'#ff5068',borderVisible:false,wickUpColor:'#00d9c5',wickDownColor:'#ff5068',priceFormat:{type:'price',precision:p,minMove:m}});this.candles.setData(data.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close})));this.volume=this.chart.addSeries(L.HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'',lastValueVisible:false,priceLineVisible:false});this.volume.setData(data.map(x=>({time:x.time,value:x.volume,color:x.close>=x.open?'rgba(0,205,185,.55)':'rgba(219,65,89,.55)'})));this.volume.priceScale().applyOptions({scaleMargins:{top:.82,bottom:0}});this._indicators();this.chart.timeScale().fitContent();this._crosshair();this._clicks();this._restore();this.render();this._countdown();this.ro=new ResizeObserver(()=>{if(this.chart){this.chart.applyOptions({width:this.host.clientWidth,height:this.host.clientHeight});this.render()}});this.ro.observe(this.host);this.chart.timeScale().subscribeVisibleTimeRangeChange(()=>this.render())}
_indicators(){const L=window.LightweightCharts;const line=(name,color,period)=>{const s=this.chart.addSeries(L.LineSeries,{color,lineWidth:2,lastValueVisible:true,priceLineVisible:false,title:name});let a=2/(period+1),e=this.data[0].close,rows=[];this.data.forEach(x=>{e=a*x.close+(1-a)*e;rows.push({time:x.time,value:e})});s.setData(rows)};line('EMA13','#0bb8ff',13);line('EMA26','#eab84d',26);const pl=(price,title,color,style=2)=>{if(price==null)return;this.candles.createPriceLine({price,color,lineWidth:1,lineStyle:style,axisLabelVisible:true,title})};pl(this.analysis?.support,'S','#00d894');pl(this.analysis?.resistance,'R','#ff526c');if(this.analysis?.fvg?.open){pl(this.analysis.fvg.bottom,'FVG','#00d6af',3);pl(this.analysis.fvg.top,'FVG','#00d6af',3)}}
_crosshair(){const out=document.getElementById('ohlcBar');this.chart.subscribeCrosshairMove(param=>{if(!out)return;let d=param.seriesData&&param.seriesData.get(this.candles);if(!d&&this.data.length)d=this.data[this.data.length-1];if(!d)return;const pct=((d.close-d.open)/d.open*100);out.innerHTML=`O <b>${this.fmt(d.open)}</b> · H <b>${this.fmt(d.high)}</b> · L <b>${this.fmt(d.low)}</b> · C <b>${this.fmt(d.close)}</b> · <span class="${pct>=0?'up':'down'}">${pct>=0?'+':''}${pct.toFixed(2)}%</span>`})}
_countdown(){const el=document.getElementById('countdownBar');const secs={'1m':60,'5m':300,'15m':900,'1h':3600,'4h':14400,'1d':86400}[this.interval]||900;const tick=()=>{if(!el||!this.data.length)return;const remain=Math.max(0,this.data[this.data.length-1].time+secs-Math.floor(Date.now()/1000));const h=Math.floor(remain/3600),mi=Math.floor(remain%3600/60),se=remain%60;el.textContent=`${window.t('close_candle')} ${h?String(h).padStart(2,'0')+':':''}${String(mi).padStart(2,'0')}:${String(se).padStart(2,'0')}`};tick();this.countTimer=setInterval(tick,1000)}
fmt(v){const[p]=this.precision(v);return Number(v).toFixed(p)}
setTool(x){this.tool=x;this.pending=[];document.querySelectorAll('.drawbar button').forEach(b=>b.classList.toggle('active',b.dataset.tool===x))}
_clicks(){this.chart.subscribeClick(param=>{if(this.tool==='cursor'||!param.point)return;const time=this.chart.timeScale().coordinateToTime(param.point.x),price=this.candles.coordinateToPrice(param.point.y);if(time==null||price==null)return;if(this.tool==='hline'){this.drawings.push({type:'hline',price});this._save();this.render();return}if(this.tool==='sl'||this.tool==='tp'){if(this.opts.onLevelClick)this.opts.onLevelClick(this.tool,price);this.setTool('cursor');return}this.pending.push({time:Number(time),price});if(this.pending.length===2){this.drawings.push({type:this.tool,a:this.pending[0],b:this.pending[1]});this.pending=[];this._save();this.render()}})}
_save(){localStorage.setItem(`enos-draw-${this.symbol}-${this.interval}`,JSON.stringify(this.drawings))}
_restore(){try{this.drawings=JSON.parse(localStorage.getItem(`enos-draw-${this.symbol}-${this.interval}`)||'[]')}catch(e){this.drawings=[]}}
undo(){this.drawings.pop();this._save();this.render()}clear(){this.drawings=[];this._save();this.render()}
xy(pt){return{x:this.chart.timeScale().timeToCoordinate(pt.time),y:this.candles.priceToCoordinate(pt.price)}}
line(x1,y1,x2,y2,color='#57ccff',dash=''){return`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="1.4" ${dash?`stroke-dasharray="${dash}"`:''}/>`}
render(){if(!this.chart||!this.overlay)return;const w=this.host.clientWidth,h=this.host.clientHeight;this.overlay.setAttribute('viewBox',`0 0 ${w} ${h}`);let svg='';for(const d of this.drawings){if(d.type==='hline'){const y=this.candles.priceToCoordinate(d.price);if(y!=null)svg+=this.line(0,y,w,y,'#62cfff','6 4');continue}const a=this.xy(d.a),b=this.xy(d.b);if(a.x==null||b.x==null||a.y==null||b.y==null)continue;if(d.type==='trend')svg+=this.line(a.x,a.y,b.x,b.y,'#4fd5ff');else if(d.type==='rect')svg+=`<rect x="${Math.min(a.x,b.x)}" y="${Math.min(a.y,b.y)}" width="${Math.abs(a.x-b.x)}" height="${Math.abs(a.y-b.y)}" fill="rgba(37,143,197,.12)" stroke="#38aeda"/>`;else if(d.type==='fib'){const hi=Math.max(d.a.price,d.b.price),lo=Math.min(d.a.price,d.b.price);[0,.236,.382,.5,.618,.786,1].forEach(f=>{const price=lo+(hi-lo)*f,y=this.candles.priceToCoordinate(price);if(y!=null)svg+=this.line(Math.min(a.x,b.x),y,Math.max(a.x,b.x),y,'#b489ff','4 3')+`<text x="${Math.max(a.x,b.x)+4}" y="${y-2}" fill="#c8a8ff" font-size="9">${f} ${this.fmt(price)}</text>`})}}const A=this.analysis;if(A?.pattern){for(const k of ['upper','lower']){const z=A.pattern[k];if(z){const a=this.xy({time:z.t1,price:z.p1}),b=this.xy({time:z.t2,price:z.p2});if(a.x!=null&&b.x!=null)svg+=this.line(a.x,a.y,b.x,b.y,'#00d8c6','6 4')}}}if(A?.markers){A.markers.slice(-24).forEach(m=>{const x=this.chart.timeScale().timeToCoordinate(m.time),y=this.candles.priceToCoordinate(m.price);if(x==null||y==null)return;const c=m.kind==='POINT_E'?'#aa75ff':m.kind==='ENTRY'?'#ffffff':m.kind==='RETEST'?'#ffd15e':m.kind==='BREAKOUT'?'#ff8f57':'#00d8c6';svg+=`<circle cx="${x}" cy="${y}" r="3" fill="${c}"/><text x="${x+4}" y="${y+(m.side==='below'?13:-7)}" fill="${c}" font-size="9">${m.label}</text>`})}this.overlay.innerHTML=svg;this._paper()}
_paper(){this.paperLayer.innerHTML='';for(const p of this.positions.filter(x=>x.symbol===this.symbol)){this._paperLine(p,'entry',p.entry,'ENTRY','level-entry',false);this._paperLine(p,'sl',p.sl,'SL','level-sl',true);this._paperLine(p,'tp1',p.tp1,'TP1','level-tp',true);this._paperLine(p,'tp2',p.tp2,'TP2','level-tp',true)}}
_paperLine(pos,key,price,label,cls,drag){const y=this.candles.priceToCoordinate(price);if(y==null)return;const d=document.createElement('div');d.className=`price-level ${cls}`;d.style.top=`${y}px`;const tag=document.createElement('span');tag.textContent=`${label} ${this.fmt(price)} · PAPER ${pos.direction} ${pos.leverage}x`;d.appendChild(tag);if(drag){d.onpointerdown=e=>{e.preventDefault();d.setPointerCapture(e.pointerId);const move=ev=>{const r=this.host.getBoundingClientRect(),yy=ev.clientY-r.top,pr=this.candles.coordinateToPrice(yy);if(pr!=null){d.style.top=yy+'px';tag.textContent=`${label} ${this.fmt(pr)}`;d._price=pr}};const up=()=>{d.removeEventListener('pointermove',move);d.removeEventListener('pointerup',up);if(d._price!=null&&this.opts.onDragLevel)this.opts.onDragLevel(pos.id,key,d._price)};d.addEventListener('pointermove',move);d.addEventListener('pointerup',up)}}this.paperLayer.appendChild(d)}
}
window.ENOSChart=ENOSChart;
