services:
  - type: web
    name: nova-gpt-trade
    env: python
    pythonVersion: 3.10
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
      - key: RENDER_PYTHON_BUILD_STRATEGY
        value: pip
    sync: false
